version: 2

# before:
#   hooks:

builds:
  - id: macos
    builder: rust
    flags:
      - --release
    targets:
      - aarch64-apple-darwin
      - x86_64-apple-darwin
      - x86_64-pc-windows-msvc

  - id: windows
    builder: rust
    flags:
      - --release
    targets:
      - x86_64-pc-windows-msvc

archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{- 
      if eq .Arch "amd64" }}x86_64{{- 
      else if eq .Arch "386" }}i386{{- 
      else if eq .Arch "arm64" }}arm64{{- 
      else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^tools:"
      - "^non-code:"

release:
  footer: >-
  
